header:
  license:
    spdx-id: MIT
    copyright-owner: seqyuan
  paths-ignore:
    - "*.md"
    - ".github/workflows/*.yml"
    - ".github/workflows/*.yaml"
    - "*.yaml"
    - ".gitignore"
    - "go.mod"
    - "go.sum"
    - "test*.sh"
    - "*.sh"
